services:
  - type: web
    name: stock-volume-monitor
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 600 --log-level info
    envVars:
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false
      - key: ACCESS_TOKEN
        sync: false
      - key: REQUEST_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: stock_volumes_db
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.7

